server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

#다국어 파일 설정
spring:
  messages:
    basename: messages # 우리가 사용할 message 파일의 이름
  # SWAGGER 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # spring security 설정 -> id, pw가 고정되어 있으므로 적절하지 않다
  security:
    user:
      name: nitro
      password: password1234

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"